# Generated by Django 4.1.2 on 2022-12-02 01:32

import accounts.utils.custom_email_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_introduction_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=accounts.utils.custom_email_field.LowercaseEmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
