# Generated by Django 4.1.2 on 2022-10-13 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='institution',
        ),
    ]
