# Generated by Django 4.1.2 on 2022-11-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_info', '0004_alter_registration_cunyfirst_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='summary',
            field=models.TextField(verbose_name='Detail (introduce more about this meeting)'),
        ),
    ]
