# Generated by Django 4.1.2 on 2022-11-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_info', '0005_alter_meeting_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cunyfirst_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUNYfirst ID (optional)'),
        ),
    ]
