# Generated by Django 4.1.2 on 2023-03-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_info', '0007_alter_registration_cunyfirst_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cunyfirst_id',
            field=models.CharField(max_length=20, verbose_name='CUNYfirst ID'),
        ),
    ]
