# Generated by Django 4.1.2 on 2022-10-14 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('subject', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('way_of_meeting', models.CharField(choices=[('online', 'online'), ('in-person', 'in-person'), ('online and in-person', 'online and in-person')], max_length=20)),
                ('meeting_time', models.DateTimeField()),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional notes (optional)')),
                ('publisher', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cunyfirst_id', models.CharField(blank=True, max_length=20, null=True)),
                ('meeting', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring_info.meeting')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
