# Generated by Django 4.1.2 on 2022-10-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_info', '0002_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
