# Generated by Django 4.1.2 on 2022-10-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_info', '0003_delete_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='cunyfirst_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CUNYFirst ID (optional)'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tutoring_info.meeting'),
        ),
    ]
