name: Build React App

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm'
        # An error will be thrown with `cache: 'npm'`:
        # /home/runner/.npm
        # Error: Dependencies lock file is not found in /home/runner/work/tutoring/tutoring. Supported file patterns: package-lock.json,npm-shrinkwrap.json,yarn.lock

    - name: Install dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Build tha app
      run: npm run build --if-present
      working-directory: ./frontend

    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: build
        path: frontend/build/
